# -*- coding: utf-8 -*-
"""CERTAINTY FACTOR (CF) gejala flu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PqBk0diGqDdJdQR63goyRr-ZKRMR12Vm
"""

gejala_user = {
    "demam": 0.7,
    "batuk": 0.5,
    "sakit_tenggorokan": 0.6
}

pengetahuan = {
    "flu": {
        "demam": 0.8,
        "batuk": 0.7,
        "sakit_tenggorokan": 0.6
    }
}

def hitung_cf(gejala_user, pengetahuan_pakar):
    cf_total = 0
    first = True
    for gejala, cf_user in gejala_user.items():
        if gejala in pengetahuan_pakar:
            cf_pakar = pengetahuan_pakar[gejala]
            cf = cf_user * cf_pakar
            if first:
                cf_total = cf
                first = False
            else:
                cf_total = cf_total + cf * (1 - cf_total)
    return cf_total

cf_flu = hitung_cf(gejala_user, pengetahuan["flu"])
print(f"CF diagnosis flu : {cf_flu:.2f}")

"""1) Kondisi dimana syntax masih dalam keadaan asli (sebelum dialakukan perubahan)"""

gejala_user = {
    "demam": 0.2,
    "batuk": 0.5,
    "sakit_tenggorokan": 0.6
}

pengetahuan = {
    "flu": {
        "demam": 0.2,
        "batuk": 0.7,
        "sakit_tenggorokan": 0.6
    }
}

def hitung_cf(gejala_user, pengetahuan_pakar):
    cf_total = 0
    first = True
    for gejala, cf_user in gejala_user.items():
        if gejala in pengetahuan_pakar:
            cf_pakar = pengetahuan_pakar[gejala]
            cf = cf_user * cf_pakar
            if first:
                cf_total = cf
                first = False
            else:
                cf_total = cf_total + cf * (1 - cf_total)
    return cf_total

cf_flu = hitung_cf(gejala_user, pengetahuan["flu"])
print(f"CF diagnosis flu : {cf_flu:.2f}")

"""2) Pengaruh: Fungsi hitung_cf mengalikan nilai CF dari user dan pakar per gejala, kemudian menggabungkannya dengan formula:

cf_total = cf_total + cf * (1 - cf_total)

pada bagian ini terdapat 3 kemungkinan yaitu :
1. "demam" menjadi 0.2 pada bagian gejala_user saja, maka hasilnya :

Sekarang pakar percaya demam penting, tapi user mengaku hanya mengalami sedikit demam.

Produk 0.2 × 0.8 = 0.16, lagi-lagi kontribusi lemah.

CF akhir tetap berkurang dari sebelumnya.

2. "demam" menjadi 0.2 pada bagian pengetahuan saja, maka hasilnya :

Meskipun user percaya mereka demam (0.7), pakar menganggap demam tidak signifikan untuk diagnosis flu (0.2).

Maka produk 0.7 × 0.2 = 0.14, kontribusi yang jauh lebih kecil dibanding sebelumnya (0.56).

Diagnosis masih terbentuk dari gejala lain, tapi tidak sekuat sebelumnya.

3. dan jika "demam" menjadi 0.2 pada keduanya, maka hasilnya :

Baik user maupun pakar sama-sama tidak yakin bahwa demam relevan.

Produk 0.2 × 0.2 = 0.04, sangat kecil kontribusinya.

Karena gejala utama kontribusinya rendah, diagnosis flu menjadi semakin lemah.
"""

gejala_user = {
    "demam": 0.7,
    "batuk": 0.5,
    "sakit_tenggorokan": 0.6,
    "hidung_tersumbat":0.4,
    "pilek":0.3,
    "sesak_nafas":0.2,
    "kepala_berat":0.7,
    "nyeri_tenggorokan":0.5
}

pengetahuan = {
    "flu": {
        "demam": 0.8,
        "batuk": 0.7,
        "sakit_tenggorokan": 0.6,
        "hidung_tersumbat":0.2,
        "pilek":0.6,
        "sesak_nafas":0.7,
        "kepala_berat":0.3,
        "nyeri_tenggorokan":0.4
    }
}

def hitung_cf(gejala_user, pengetahuan_pakar):
    cf_total = 0
    first = True
    for gejala, cf_user in gejala_user.items():
        if gejala in pengetahuan_pakar:
            cf_pakar = pengetahuan_pakar[gejala]
            cf = cf_user * cf_pakar
            if first:
                cf_total = cf
                first = False
            else:
                cf_total = cf_total + cf * (1 - cf_total)
    return cf_total

cf_flu = hitung_cf(gejala_user, pengetahuan["flu"])
print(f"CF diagnosis flu : {cf_flu:.2f}")

"""3) Dari perbedaan di atas maka dapat ditarik kesimpulan bahwa perbedaan yang hanya 3 gejala saja dan +5 gejala tambahan adalah :

- Semakin banyak gejala relevan yang diberikan, semakin tinggi keyakinan sistem CF terhadap suatu diagnosis.

- Dengan 3 gejala, sistem dapat memprediksi, tapi masih bisa ragu.

- Dengan 8 gejala yang cocok, sistem semakin yakin karena lebih banyak bukti yang menguatkan diagnosis.
"""