# -*- coding: utf-8 -*-
"""Fuzz Logic Suhu dan Kelembaban.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tSnGuH5unRdm-8o5dixShWEbRkygUc16
"""

!pip install scikit-fuzzy

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
import matplotlib.pyplot as plt

#Input variables
temperature = ctrl. Antecedent(np.arange(15, 41, 1), 'temperature')
humidity = ctrl.Antecedent(np.arange(20, 101, 1), 'humidity')
import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
import matplotlib.pyplot as plt

#Input variables
temperature = ctrl.Antecedent(np.arange(15, 41, 1), 'temperature')
humidity = ctrl.Antecedent(np.arange(20, 101, 1), 'humidity')

# Output variable
fan_speed = ctrl.Consequent(np.arange(0, 101, 1), 'fan_speed')

#Membership functions for temperature
temperature['dingin'] = fuzz.trapmf(temperature.universe, [15, 15, 20, 24])
temperature['nyaman'] = fuzz.trimf(temperature.universe, [22, 26, 30])
temperature['panas'] = fuzz.trapmf(temperature.universe, [28, 32, 40, 40])

# Membership functions for humidity
humidity['kering'] = fuzz.trapmf(humidity.universe, [20, 20, 30, 45])
humidity['normal'] = fuzz.trimf(humidity.universe, [35, 50, 65])
humidity['lembab'] = fuzz.trapmf(humidity.universe, [55, 70, 100, 100])

#Membership functions for fan speed
fan_speed['mati'] = fuzz.trimf(fan_speed.universe, [0, 0, 25])
fan_speed['rendah'] = fuzz.trimf(fan_speed.universe, [0, 25, 50])
fan_speed['sedang'] = fuzz.trimf(fan_speed.universe, [25, 50, 75])
fan_speed['tinggi'] = fuzz.trimf(fan_speed.universe, [50, 75, 100])
fan_speed['maksimal'] = fuzz.trimf(fan_speed.universe, [75, 100, 100])

#Visualize membership functions
temperature.view()
humidity.view()
fan_speed.view()

#Define fuzzy rules
rule1 = ctrl.Rule(temperature['dingin'] & humidity['kering'], fan_speed['mati'])
rule2 = ctrl.Rule(temperature['dingin'] & humidity['normal'], fan_speed['mati'])
rule3 = ctrl.Rule(temperature['dingin'] & humidity['lembab'], fan_speed['rendah'])
rule4 = ctrl.Rule(temperature['nyaman'] & humidity['kering'], fan_speed['rendah'])
rule5 = ctrl.Rule(temperature['nyaman'] & humidity['normal'], fan_speed['sedang'])
rule6 = ctrl.Rule(temperature['nyaman'] & humidity['lembab'], fan_speed['tinggi'])
rule7 = ctrl.Rule(temperature['panas'] & humidity['kering'], fan_speed['tinggi'])
rule8 = ctrl.Rule(temperature['panas'] & humidity['normal'], fan_speed['tinggi'])
rule9 = ctrl.Rule(temperature['panas'] & humidity['lembab'], fan_speed['maksimal'])

#Create control system
ac_ctrl = ctrl.ControlSystem([rule1, rule2, rule3, rule4, rule5, rule6, rule7, rule8, rule9])
ac = ctrl.ControlSystemSimulation(ac_ctrl)

#Input values
ac.input['temperature'] = 30
ac.input['humidity'] = 75

#Compute result
ac.compute()
print(f"Untuk suhu 30°C dan kelembaban 75%, kecepatan kipas AC: {ac.output['fan_speed']:.2f}%")

#Visualize result
fan_speed.view(sim=ac)
plt.show()

"""1) Kondisi sytax saat masih berada pad kondisi asli (sebelum dilakukan perubahan dan modifikasi)"""

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
import matplotlib.pyplot as plt

#Input variables
temperature = ctrl. Antecedent(np.arange(15, 41, 1), 'temperature')
humidity = ctrl.Antecedent(np.arange(20, 101, 1), 'humidity')
import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
import matplotlib.pyplot as plt

#Input variables
temperature = ctrl.Antecedent(np.arange(15, 41, 1), 'temperature')
humidity = ctrl.Antecedent(np.arange(20, 101, 1), 'humidity')

# Output variable
fan_speed = ctrl.Consequent(np.arange(0, 101, 1), 'fan_speed')

#Membership functions for temperature
temperature['dingin'] = fuzz.trapmf(temperature.universe, [15, 15, 20, 24])
temperature['nyaman'] = fuzz.trimf(temperature.universe, [22, 26, 30])
temperature['panas'] = fuzz.trapmf(temperature.universe, [28, 32, 40, 40])
temperature['veryhot'] = fuzz.trapmf(temperature.universe, [35, 50, 50, 50])

# Membership functions for humidity
humidity['kering'] = fuzz.trapmf(humidity.universe, [20, 20, 30, 45])
humidity['normal'] = fuzz.trimf(humidity.universe, [35, 50, 65])
humidity['lembab'] = fuzz.trapmf(humidity.universe, [55, 70, 100, 100])
humidity['veryvery'] = fuzz.trapmf(humidity.universe, [75, 100, 100, 100])


#Membership functions for fan speed
fan_speed['mati'] = fuzz.trimf(fan_speed.universe, [0, 0, 25])
fan_speed['rendah'] = fuzz.trimf(fan_speed.universe, [0, 25, 50])
fan_speed['sedang'] = fuzz.trimf(fan_speed.universe, [25, 50, 75])
fan_speed['tinggi'] = fuzz.trimf(fan_speed.universe, [50, 75, 100])
fan_speed['maksimal'] = fuzz.trimf(fan_speed.universe, [75, 100, 100])
fan_speed['fullspeed'] = fuzz.trimf(fan_speed.universe, [95, 100, 100])

#Visualize membership functions
temperature.view()
humidity.view()
fan_speed.view()

#Define fuzzy rules
rule1 = ctrl.Rule(temperature['dingin'] & humidity['kering'], fan_speed['mati'])
rule2 = ctrl.Rule(temperature['dingin'] & humidity['normal'], fan_speed['mati'])
rule3 = ctrl.Rule(temperature['dingin'] & humidity['lembab'], fan_speed['rendah'])

rule4 = ctrl.Rule(temperature['nyaman'] & humidity['kering'], fan_speed['rendah'])
rule5 = ctrl.Rule(temperature['nyaman'] & humidity['normal'], fan_speed['sedang'])
rule6 = ctrl.Rule(temperature['nyaman'] & humidity['lembab'], fan_speed['tinggi'])

rule7 = ctrl.Rule(temperature['panas'] & humidity['kering'], fan_speed['tinggi'])
rule8 = ctrl.Rule(temperature['panas'] & humidity['normal'], fan_speed['tinggi'])
rule9 = ctrl.Rule(temperature['panas'] & humidity['lembab'], fan_speed['maksimal'])

#Rule Baru
rule10 = ctrl.Rule(temperature['veryhot'] & humidity['veryvery'], fan_speed['fullspeed'])

#Create control system
ac_ctrl = ctrl.ControlSystem([rule1, rule2, rule3, rule4, rule5, rule6, rule7, rule8, rule9, rule10])
ac = ctrl.ControlSystemSimulation(ac_ctrl)

#Input values
ac.input['temperature'] = 22
ac.input['humidity'] = 75

#Compute result
ac.compute()
print(f"Untuk suhu 30°C dan kelembaban 75%, kecepatan kipas AC: {ac.output['fan_speed']:.2f}%")

#Visualize result
fan_speed.view(sim=ac)
plt.show()

"""2) Jika dilakukan perubahan pada suhu 22 C, maka yang terjadi adalah :

1. Fungsi keanggotaan suhu :

- Dingin: berada di ujung kanan dari trapmf → nilai masih sekitar 0.5

- Nyaman: berada di ujung kiri dari trimf → nilai sekitar 0.0 – 0.2

- Panas: tidak termasuk → nilai 0

2. Aturan yang aktif (kemungkinan) :

Yang mungkin aktif sebagian:

- Rule 3: karena suhu 22°C masih cukup dingin dan kelembaban 75% adalah "lembab" → output: fan_speed rendah

- Rule 6: karena suhu 22°C sedikit memiliki keanggotaan "nyaman" → output: fan_speed tinggi, tapi kecil kontribusinya

3. Fan speed :

- Suhu dingin → sistem cenderung tidak menyalakan kipas terlalu kencang

- Namun, karena kelembaban tinggi, ada sedikit dorongan untuk meningkatkan kecepatan kipas
"""

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
import matplotlib.pyplot as plt

#Input variables
temperature = ctrl. Antecedent(np.arange(15, 41, 1), 'temperature')
humidity = ctrl.Antecedent(np.arange(20, 101, 1), 'humidity')
import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
import matplotlib.pyplot as plt

#Input variables
temperature = ctrl.Antecedent(np.arange(15, 41, 1), 'temperature')
humidity = ctrl.Antecedent(np.arange(20, 101, 1), 'humidity')

# Output variable
fan_speed = ctrl.Consequent(np.arange(0, 101, 1), 'fan_speed')

#Membership functions for temperature
temperature['dingin'] = fuzz.trapmf(temperature.universe, [15, 15, 20, 24])
temperature['nyaman'] = fuzz.trimf(temperature.universe, [22, 26, 30])
temperature['panas'] = fuzz.trapmf(temperature.universe, [28, 32, 40, 40])
temperature['veryhot'] = fuzz.trapmf(temperature.universe, [35, 50, 50, 50])

# Membership functions for humidity
humidity['kering'] = fuzz.trapmf(humidity.universe, [20, 20, 30, 45])
humidity['normal'] = fuzz.trimf(humidity.universe, [35, 50, 65])
humidity['lembab'] = fuzz.trapmf(humidity.universe, [55, 70, 100, 100])
humidity['veryvery'] = fuzz.trapmf(humidity.universe, [75, 100, 100, 100])


#Membership functions for fan speed
fan_speed['mati'] = fuzz.trimf(fan_speed.universe, [0, 0, 25])
fan_speed['rendah'] = fuzz.trimf(fan_speed.universe, [0, 25, 50])
fan_speed['sedang'] = fuzz.trimf(fan_speed.universe, [25, 50, 75])
fan_speed['tinggi'] = fuzz.trimf(fan_speed.universe, [50, 75, 100])
fan_speed['maksimal'] = fuzz.trimf(fan_speed.universe, [75, 100, 100])
fan_speed['fullspeed'] = fuzz.trimf(fan_speed.universe, [95, 100, 100])

#Visualize membership functions
temperature.view()
humidity.view()
fan_speed.view()

#Define fuzzy rules
rule1 = ctrl.Rule(temperature['dingin'] & humidity['kering'], fan_speed['mati'])
rule2 = ctrl.Rule(temperature['dingin'] & humidity['normal'], fan_speed['mati'])
rule3 = ctrl.Rule(temperature['dingin'] & humidity['lembab'], fan_speed['rendah'])

rule4 = ctrl.Rule(temperature['nyaman'] & humidity['kering'], fan_speed['rendah'])
rule5 = ctrl.Rule(temperature['nyaman'] & humidity['normal'], fan_speed['sedang'])
rule6 = ctrl.Rule(temperature['nyaman'] & humidity['lembab'], fan_speed['tinggi'])

rule7 = ctrl.Rule(temperature['panas'] & humidity['kering'], fan_speed['tinggi'])
rule8 = ctrl.Rule(temperature['panas'] & humidity['normal'], fan_speed['tinggi'])
rule9 = ctrl.Rule(temperature['panas'] & humidity['lembab'], fan_speed['maksimal'])

#Rule Baru
rule10 = ctrl.Rule(temperature['veryhot'] & humidity['veryvery'], fan_speed['fullspeed'])

#Create control system
ac_ctrl = ctrl.ControlSystem([rule1, rule2, rule3, rule4, rule5, rule6, rule7, rule8, rule9, rule10])
ac = ctrl.ControlSystemSimulation(ac_ctrl)

#Input values
ac.input['temperature'] = 28
ac.input['humidity'] = 75

#Compute result
ac.compute()
print(f"Untuk suhu 30°C dan kelembaban 75%, kecepatan kipas AC: {ac.output['fan_speed']:.2f}%")

#Visualize result
fan_speed.view(sim=ac)
plt.show()

"""3) Kenapa pada suhu 28 C memiliki keanggotaan "Nyaman" dan "Panas" ? karena

a) fungsi keanggotaan suhunya :
-  ‘Nyaman’ adalah fungsi segitiga (trimf) dari:
1. 22°C (nilai keanggotaan = 0)

2. 26°C (nilai keanggotaan = 1)

3. 30°C (nilai keanggotaan = 0)

-  ‘Panas’ adalah fungsi trapesium (trapmf) dari:
1. 28°C (mulai naik dari 0)

2. 32°C (nilai keanggotaan = 1)

3. 40°C (tetap 1)

b) maka hal yang terjadi pada suhu dengan temperatur 28 C adalah :

- Pada temperature['nyaman'], 28°C berada di sisi kanan dari segitiga:

1. Nilai keanggotaan fuzzy bisa dihitung secara linear.

2. Di titik 28°C, nilai keanggotaan ≈ 0.5

- Pada temperature['panas'], 28°C adalah titik awal naik:

1. Nilai keanggotaan fuzzy ≈ 0.0 ~ 0.2 (tergantung kemiringan trapezium awal)
"""